services:
  web:
    build: .
    ports:
      - "443:4000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

      
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
  uploads:
  node_modules:
